"use client";
import React from 'react';
import Image from 'next/image';
import { CircleCheck } from 'lucide-react';

type RecommendationProps = {
  onDownload?: () => void;
  uploadedImage?: File | null;
  onUpload?: () => void; // Added prop for upload button click handler
}

const Recommendation = ({ onDownload, uploadedImage, onUpload }: RecommendationProps) => {
  // Sample recommendation data - in a real app, this would come from props or an API
  const recommendations = [
    { id: 1, src: '/one.jpeg', alt: 'Diamond Necklace' },
    { id: 2, src: '/one.jpeg', alt: 'Emerald Necklace' },
    { id: 3, src: '/one.jpeg', alt: 'Ruby Necklace' },
    { id: 4, src: '/one.jpeg', alt: 'Sapphire Necklace' },
  ];

  return (
    <div className="bg-white rounded-xl px-10 max-w-6xl mx-auto pb-10">
      {/* Progress Steps */}
      <div className="py-8 flex justify-center items-center">
        <div className="flex items-center gap-3">
          <div className="flex flex-col items-center">
            <CircleCheck className="w-10 h-10 text-green-900 fill-green-900 stroke-white" />
            <span className="mt-2 text-base font-medium">Upload</span>
          </div>
          
          <div className="w-32 h-[2px] bg-green-900"></div>
          
          <div className="flex flex-col items-center">
            <CircleCheck className="w-10 h-10 text-green-900 fill-green-900 stroke-white" />
            <span className="mt-2 text-base font-medium">Annotations</span>
          </div>

          <div className="w-32 h-[2px] bg-green-900"></div>
          
          <div className="flex flex-col items-center">
            <CircleCheck className="w-10 h-10 text-green-900 fill-green-900 stroke-white" />
            <span className="mt-2 text-base font-medium">Suggestion</span>
          </div>
        </div>
      </div>

      {/* Uploaded Image Preview */}
      {uploadedImage && (
        <div className="mt-8">
          <h3 className="text-xl font-semibold mb-4">Uploaded Image</h3>
          <div className="max-w-md mx-auto">
            <img
              src={URL.createObjectURL(uploadedImage)}
              alt="Uploaded preview"
              className="w-full h-auto rounded-lg"
            />
          </div>
        </div>
      )}

      {/* Recommendation Section */}
      <div className="mt-8">
        {/* Recommendation Heading and Upload Button Row */}
        <div className="flex justify-between items-center mb-3">
          <div>
              <h2 className="text-3xl font-bold">Recommendation</h2>
              <div className="flex justify-end mb-8">
              <p className="text-gray-600">
                Below are few recommendation generated by our system
              </p>
            </div>
          </div>
          <button 
            onClick={onUpload}
            className="bg-green-900 text-white py-2 px-6 rounded-md text-lg font-medium hover:bg-green-800 transition-colors"
          >
            Upload
          </button>
        </div>

        {/* Recommendation Text to the Right */}
     
        {/* Recommendation Grid */}
        <div className="bg-gray-100 rounded-xl p-6 mb-6">
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
            {recommendations.map((item) => (
              <div key={item.id} className="relative overflow-hidden rounded-lg">
                <Image 
                  src={item.src}
                  alt={item.alt}
                  width={300}
                  height={300}
                  className="w-full h-auto object-cover"
                />
              </div>
            ))}
          </div>
        </div>

        {/* Download Button */}
        <div className="flex justify-center mt-8">
          <button 
            onClick={onDownload}
            className="bg-green-900 text-white py-3 px-8 rounded-md text-lg font-medium hover:bg-green-800 transition-colors"
          >
            Download
          </button>
        </div>
      </div>
    </div>
  );
};

export default Recommendation;